### PR TITLE
Add VirtualBox version detection to Vagrantfile

### PR DESCRIPTION
**Pull request by seanjreilly**
The vagrant box will intelligently attempt to use an appropriate
base box that matches the installed version of VirtualBox.

Versions of VirtualBox older than 4.3.6 are assumed to be 4.2.

### CODE REVIEW

**Comment by alexmuller** [comment]
This looks awesome and way better than what's in my branch (just outright changing the box to use the latest version).

2 space indent instead of 4 though please.

**Comment by seanjreilly** [comment]
Indent fixed.

**Comment by robyoung** [comment]
Woot! :beers:
1. Do we need to match the exact patch revision or can we rely on the major / minor parts?
2. (at the risk of starting a flame war again) could you squash the second commit into the first?

**Comment by seanjreilly** [comment]
1. We should match the entire revision. The good news is that every x.y release has exactly one revision all the way down, and it's consistent across multiple platforms. So 4.3 _should_ always be _exactly_ "4.3.6r91406". But if this policy ever changes (aka two stable 4.3 releases), the Vagrantfile should detect it as soon as possible, because if the patch version changes, the VirtualBox extensions might change as well, and that's the whole reason behind this feature. Therefore, I'd like to keep the version matching as specific and pedantic as possible.
2. Done.

**Pull request merged**
