### PR TITLE
Don't use NFS on VMWare

### PR DESCRIPTION
**Pull request by jabley**
See http://mitchellh.com/comparing-filesystem-performance-in-virtual-machines

Personally, I find IO performance under VMWare acceptable. NFS sometimes
seems a little slow when syncing between the guest and the host.

### CODE REVIEW

**Comment by easternbloc** [comment]
It's very noticeable without NFS on a mac when working on spotlight. supervisor takes a lot longer to see the changes in js files (and restart). I'm sure @annapowellsmith, @alexmuller, @tombooth will agree with me on this one!

**Comment by tombooth** [comment]
I've disabled NFS as it seems worse for me in terms of supervisor picking up changes

**Comment by easternbloc** [comment]
We all just had a quick chat about this and it should probably be configurable...

**Comment by jabley** [comment]
OK, I'll take a look at making it more configurable.

**Pull request merged**
