### PR TITLE
Explain how perfplat.dev is supposed to work

### PR DESCRIPTION
**Pull request by pwaller**
This was the first thing that I didn't understand since the machine worked but not as advertised (I missed the note after "we've tested with Vagrant >=1.3.0").

/cc @jabley

### CODE REVIEW

**Comment by pwaller** [comment]
Hmm, it still doesn't work even after having installed it using `vagrant plugin install vagrant-dns`. I also destroyed and recreated the machine, but `host www.perfplat.dev`, etc, returns NXDOMAIN.

**Comment by alexmuller** [comment]
This is more clear, thanks! :+1:

**Comment by fawkesley** [comment]
@pwaller Alas, [vagrant-dns only supports OS X](https://github.com/BerlinVagrant/vagrant-dns/blob/master/PLATFORM_SUPPORT.md)

Nice wording change, probably even better would be to say "If you're on OS X you can install..." :)

**Comment by pwaller** [comment]
Ah, which might explain why it still doesn't work. Heh.

**Pull request merged**
