### PR TITLE
Tell developers where to download supported virtualbox editions

### PR DESCRIPTION
**Pull request by roc**
- reads like:

```
Virtualbox version {YOURVERSION} is not supported by pp-development. See README.md.
Supported: ["SUPPORTED_VERSION"] --> ["http://download.virtualbox.org/virtualbox/SUPPORTED_VERSION"]
```

Aside: Whilst I dislike this approach that absolutely halts all Vagrant operations because of an idea of version support — including calls for non-write functions like the status of the current box — I think if we're doing this we should at least let people know where to find a copy of the supported version.

### CODE REVIEW

**Comment by fawkesley** [comment]
This is cute, but I'm not mad about the fact that it links me to an OS X image!!

```
$ vagrant up
Virtualbox version 4.2.10r84104 is not supported by pp-development. See README.md.
Supported: ["4.3.6r91406"] --> ["http://download.virtualbox.org/virtualbox/4.3.6/VirtualBox-4.3.6-91406-OSX.dmg"]
```

**Comment by fawkesley** [comment]
Suggest linking to [http://download.virtualbox.org/virtualbox/4.3.6/](http://download.virtualbox.org/virtualbox/4.3.6/) instead as that contains all platforms.
(And it was ridiculously difficult to find from the website!!)

**Comment by nick-gravgaard** [comment]
I thought about that too, but won't Linux users rather use their package management system? The message could say something like "OS X users should use this image [link], and apt users can pin their version like this ..."

**Comment by roc** [comment]
@nickgravgaard Paul's suggestion feels like a good compromise. :heart: Someone merge this before I go postal pls :heart:

**Pull request merged**
