### PR TITLE
Add virtualbox 4.3.8

### PR DESCRIPTION
**Pull request by robyoung**
- Refactor how the box details are generated.
- Add Virtualbox 4.3.8

### CODE REVIEW

**Comment by pwaller** [comment]
LGTM. Have you had a chance to consider #54?

**Comment by robyoung** [comment]
Not yet, no. We have two general directions we can take here. Build more on the client, start from a completely bare box and build up from scratch (vagrant-vbguest would help there) or build more into the base box and have to provide different base boxes for different versions of VirtualBox.

Ultimately you (the client of the platform) shouldn't have to know very much at all about how the platform fits together. You need a virtual machine you can spin up that exposes the same APIs that the platform does so that you can test develop against them. To me that sounds like building more into the image. That is just my opinion though, we (the Performance Platform) still need to have that conversation.

**Comment by pwaller** [comment]
On that front, it's unfortunate - the way we get development machines we can all access is through AWS EC2, and virtualbox doesn't run there at all. That means we can't have a shared testing environment over on our side (and we don't have access to preview). Which maybe doesn't matter much except that it doesn't work on Ian's windows machine either. We're happy working around that for now but it blows a hole in the idea that "put it in virtualbox, then it can run anywhere" :(.

**Comment by pwaller** [comment]
(Which I had accepted as truth before now).

**Comment by robyoung** [comment]
Exactly, so if we can build everything into an image that you just need to run it should be much easier. If we can automate a pipeline for building the images the job of targeting more environments becomes a little smaller. We could even target EC2!

**Pull request merged**
